name: CI Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-integration.txt
    - name: Bring Server up
      run: |
        docker build -t minerva-referral:latest .
        docker run -d --name=minerva-referral-instance --env-file .env -p 8000:8000 minerva-referral
    - name: Test with pytest
      run: |
        pytest integration_test
